### ISSUE TITLE
Confusing error when injecting an abstract class

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#122]
I accidentally had an abstract class parameter in a request scoped bean. At runtime I got this message:

`java.lang.IllegalStateException: Missing bean for type:class hydraulic.parts.tasks.linux.BuildLinuxJVMAppTask name:buildLinuxJVM`

There are two ways to improve this error:

1. More precise exception than ISE
2. It doesn't say _which_ bean is missing, only what was being constructed at the time. I had to stare at the dependency list for a few moments to realize what might be making it unhappy.

**Comment by mikehearn** [comment]
Oh and of course, it's a bit confusing that this was only detected at runtime not compile time.

**Comment by rbygrave** [comment]
Missing dependencies for Constructor based injection is detected at compile time (but this isn't the case for field or method injection).

It would be nice to add this check for the field and method injection cases noting that I believe we can only do that check as a separate pass/check at the end and would require avaje-inject to collect all the meta data for field and method injection (at the moment it actually only needs meta data for constructors as that determines the wiring order).

Hmmm.

**Comment by mikehearn** [comment]
Hmm in this case I've only been using constructor injection.

**Comment by rbygrave** [comment]
If you create a test case then we can look at it.

**Comment by rbygrave** [comment]
If you get a test case for me to look at that would be great. Thanks.

**Comment by rbygrave** [comment]
Can we close this one now @mikehearn  ?

**Comment by rbygrave** [comment]
May as well close this for now.   We can re-open as needed.
