### ISSUE TITLE
Named beans are automatically lowercased?

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#123]
It appears that the name given to a `@Named(...)` annotation is automatically lower cased, such that if I register a bean with a name that uses mixed case in the builder, it then cannot be found. Is that right? Why is the string being case-mangled here?

**Comment by rbygrave** [comment]
The qualifiers are case insensitive. More specifically, to pass TCK tests the qualifiers are case insensitive.   So `@Named("blue")` and `@Blue` both are the same qualifier etc.

> register a bean with a name that uses mixed case in the builder, it then cannot be found. Is that right?

No, that should work fine and there are tests for that.

**Comment by mikehearn** [comment]
OK, I've stopped using named beans - not sure why I saw lowercased names but you can close this if you like, as I probably won't try and revisit this to figure out exactly what was going on.

**Comment by rbygrave** [comment]
Ok closing.  Note that I do expect qualifier names to be lower cased as they are expected to be case insensitive as per the TCK tests.
