### ISSUE TITLE
list() doesn't seem to work for request scopes

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#124]
list() requires calls to `Builder.isAddBeanFor` but it seems the only place that's generated is the `$DI` class for singletons, not request scoped objects.

**Comment by rbygrave** [comment]
That could be done in DRequestScope by combining the results of  `BeanScope beanScope;` and `ConcurrentHashMap<String, Object> supplied;`.

Noting that `ConcurrentHashMap<String, Object> supplied;` is not an optimal structure to support `list()`.  Do you want to play around with an implementation for that?

**Comment by mikehearn** [comment]
I can take a look I guess. At the moment I'm fiddling with my code to see if I can "swim with the current" so to speak and use singletons for everything instead of request scoping.

**Comment by rbygrave** [comment]
Deeming this fixed in 6.5-RC0
