### ISSUE TITLE
No way to enumerate every object in the scope

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#125]
In my app the user can pick an object to invoke from the command line (more or less). So, I'd like to be able to enumerate all the beans in a scope, including the pre-supplied beans, and access their names as well as their class types. That way I can build a list of all available objects for the UI.

**Comment by rbygrave** [comment]
The instances are held in DBeanMap - https://github.com/avaje/avaje-inject/blob/master/inject/src/main/java/io/avaje/inject/spi/DBeanMap.java#L15

The are held as DContextEntryBean

So that seems doable. The map is keyed by canonicalName of the type.

**Comment by rbygrave** [comment]
Fixed in 6.5-RC0 via BeanScope.all()
