### ISSUE TITLE
Can't use a Factory in combination with request scope

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#126]
I don't _think_ there's any conceptual issue with this, but it won't let me create a factory for creating request scoped beans because it barfs when encountering the unknown dependencies.

**Comment by rbygrave** [comment]
Can you include a test case / example here?

**Comment by mikehearn** [comment]
I think this was a conceptual issue on my part - compile-time DI really wants to be able to see all beans ahead of time so it can do static exhaustiveness checks, and that's good! One of my beefs with Guice was the way it converted compile time errors into runtime errors. 

The combination of switching to singleton scope, creating the BeanScope manually and using the `@InjectModule(requires)` trick means I'm no longer needing request scopes, so you can close this if you like. I'm not sure it represents any real bug.

**Comment by rbygrave** [comment]
Ok cool, we will close this then.
