### ISSUE TITLE
listByAnnotation() does not work on request scope

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#127]
It seems odd I can list by type (or should be able to) on a request scope, but to list by annotation requires a BeanScope which a RequestScope isn't.

I guess I seem to be hitting a lot of issues caused by this conceptual split between global and request scopes. I'm a DI noobie so maybe there's a reason for this split that I can't see, but is there some fundamental deep reason why global scope isn't just a global variable holding a regular scope object somewhere? Given that a `@Request` scoped object is strictly more powerful (in terms of what it can accept) than a singleton scoped object, it's not totally clear to me what the benefit is. I guess to keep the compile time checking that all dependencies are present, you could have a kind of unified scope where you annotate parameters that are expected to be injected into the injector from outside its control.

**Comment by rbygrave** [comment]
This is more just an omission in the API (but would have the same implementation implications as request scope `list()`)

**Comment by rbygrave** [comment]
I'll change this to listByAnnotation() does not work/exist for request scope.

**Comment by rbygrave** [comment]
Effective list() and listByAnnotation() only work on [the underlying] BeanScope.  They don't take into account request scope created instances (which are created on demand).  

At this stage I don't think we want to change this for request scope.

**Comment by mikehearn** [comment]
Hm, OK. I don't quite follow why they can't - aren't they operating on lists of classes, not instantiated objects? But I'm using global scope at this point anyway, so I don't need this anymore. Perhaps using Request scope would be conceptually cleaner but I do need the ability to list all the beans.

**Comment by rbygrave** [comment]
Well, request scope is now gone in the experimental branch and it looks like that will stick.

So that will mean list() and listByAnnotation() will effectively work as expected as we really only have BeanScope going forward.

>  I do need the ability to list all the beans.

Yes, that will be easier in a world with only BeanScope so we should be able to do that (probably not super performant to do the "list all beans" as it's orientated to injection by "key" but it should be good enough I think).

**Comment by rbygrave** [comment]
Ok, I think we can close this - fixed in 6.5-RC0
