### ISSUE TITLE
Unnecessary compiler warning on every build

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#128]
`warning: File for type 'hydraulic.parts._DI$BeanScopeFactory' created in the last round will not be subject to annotation processing.`

I don't think this warning is actionable.

**Comment by rbygrave** [comment]
We can't really remove the warning though.

**Comment by mikehearn** [comment]
This happens when the processor forces itself into the last round using `processingOver`. What's the rationale for doing so?

**Comment by rbygrave** [comment]
We only generate `_DI$BeanScopeFactory` in the last round given at that point we have all the meta data for generating the "ordering" of how all the components are created/constructed. 

Unless we re-generate it on every round?  Is that what you are thinking?  I can't remember if I ever tried that ... hmmm.

**Comment by mikehearn** [comment]
I'm not sure, I was just wondering if it's required to go last, but I can see how that may be needed given modules. I guess re-generating on every round could also work - it's fast, after all.

**Comment by rbygrave** [comment]
> re-generating on every round

It doesn't work / we are not allowed to write the same thing multiple times. So this warning is something we have to live with.

**Comment by rbygrave** [comment]
Well **_actually_** we can get around this warning.  We just need to create the JavaFileObject earlier than the last round (but we still only write to it on the last round).

Putting this fix into the refactor scope branch. Effectively creating the JavaFileObject for the factory early.
