### ISSUE TITLE
Idea: generate a custom constructor on a module class

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#143]
When a scope has external requirements, those objects must be provided via addBean before the scope can be built. Not doing so is an error. Without DI this error would be caught by the compiler, because you wouldn't be able to instantiate your target object at all unless you passed in what it needed, but with DI dependencies come from a dynamic map. It therefore seems to make sense if a module class had a constructor that required you to pass in these beans and automatically registered them.

**Comment by rbygrave** [comment]
Yeah, this is a good idea - I like it !!

**Comment by rbygrave** [comment]
So a note is that we still want 'default' scope modules to be service loaded (which means that they must have a default constructor).  

This change this makes good sense for 'custom' scope modules. With custom scope modules they also won't ever really be service loaded. The only downside is we have this difference between custom modules and 'default' scope modules.
