### ISSUE TITLE
Idea: be able to provide a function that maps (source type, destination type) -> instance

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#147]
I have a fairly complicated graph of objects, most of which can be configured in some way. I'm using Lightbend's Config library directly here, not Avaje Config. Currently I simply have a mega-class that defines the config file format for the whole app, and reads from the underlying configs. That class is then injected as a dependency. So far, so good.

Now, I'd like to experiment with making the way config is defined and mapped to these objects a bit less ad-hoc, a bit less revolving around a config "god object". In the Config library, you can grab sub-trees of the configuration very easily, but they're always typed as Config. So the obvious thing to do is define lots of little wrapper classes that take a Config and expose functions for loading stuff from the config. Then we create them as external dependencies and inject those into the existing configurable objects.

But this isn't totally satisfying. I already _have_ objects, and they could easily read what they need from a Config directly. The wrapper types would only be to disambiguate for the injector. I can get rid of the wrappers by using the new support for named beans - this makes it a lot easier. Now I can just have a central place where I select sub-trees of the config and register them as named beans, with a naming convention such that every configurable object has a constructor parameter named something like `fooBarConfig`. No more wrapper types - nice.

But still, it isn't _perfect_. The most obvious name for a config object is just `config` but now they have to be globally unique, and that's not really an obvious rule. Also, to make a new configurable object I need to create the object and then have a central point where it's registered, just to map config tree to parameter name.

I could fix the central registration point by constructing my modules, then looping over and reflecting on the result of `provides()`. The type names would then be mapped to config locations, and beans registered with auto generated names. If I can make my configuration structure map directly to code, and as long as the convention is followed, we're good.

But fundamentally all this is a bit of a workaround. What I'd really like in this case is for the parameter name to be unimportant. If the injector doesn't seem to have a bean or factory for a parameter, it could call that function (which could itself be injected?) as a fallback before giving up. I could then use reflection metadata to figure out where in the config hierarchy the object should be configured from, select it and pass it back. Now there's no invisible dependency on the name of a parameter anymore, and the logic is generalized and configured in a central place (e.g. on the builder).

**Comment by mikehearn** [comment]
On further reflection and doing more design work, I'm no longer sure I'd actually need or use this feature for reasons related to other features planned further in the roadmap. So maybe it's not worth having or is too specialized.

**Comment by rbygrave** [comment]
Ok. I didn't fully follow what this looked like.  If we want to have another look at it perhaps a little example might help.
