### ISSUE TITLE
Gradle testAnnotationProcessor for classes under test

### ISSUE THREAD

**Issue by Travisnv** [avaje/avaje-inject#164]
Hi,

This is more than a question than a defect. I trying to use dinject for classes under test source set with gradle. For an example:

/src/test/java/

@Singleton
public class Client {

}
...
...
@CustomScope
public class Client2 {

}
---

on build.gradle

I have setup the following:

dependencies {
...
    testImplementation group: 'io.avaje', name: 'avaje-inject', version:'6.11'
    testAnnotationProcessor group: 'io.avaje', name: 'avaje-inject-generator', version:'6.11'
...
}

on the IDE itself, I see IntelliJ can find generated class from import statement. However, when I issue Gradle task `clean compileJavaTest test` I see gradle complains about not about to find the generated classes from dinject.

Can you please have a look and have any direction for using dinject for test source set ?

Thanks and Regards,
Travis

**Comment by rbygrave** [comment]
Hmmm, the above looks ok to me. Do you want to create a little example project?  I can then clone it and look.

**Comment by Travisnv** [comment]
Please have a look at: https://github.com/Travisnv/dinject-test-source-set.git

From src/test/java/test I have two client class:

If I use default scope (@Singleton), compile task work fine. However, if I use custom scope (@TestScope) for client classes, I see following error:

```
error: Failed to create module filer Attempt to recreate a file for type test.TestModule
error: Failed to create module filer Attempt to recreate a file for type test.TestModule

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
```

**Comment by rbygrave** [comment]
*> @TestScope*

Note that there is a built in @TestScope now ... it was added in version
6.13 https://github.com/avaje/avaje-inject/issues/155  With the view of
making it easier for component testing.  So have a look at that and the
associated tests in case you are looking to do something similar.

I see you are using version6.11 here so in theory that isn't the issue with
this example but note that @TestScope gets special treatment from 6.13
onwards.

I'll see if I can look at this later tonight.

Cheers, Rob.

**Comment by rbygrave** [comment]
Example:
https://github.com/avaje/avaje-inject/commit/5d75cff3cb7500912b50f20742c65c1ab1604b13#diff-b34df5e5e20ef8a5d497c4aa87fce8515f2a631588564b72a82d5ea8c24b0059R16

**Comment by Travisnv** [comment]
I have a look and see we want to archive similar object: a scope during test. However, rather than having a common test scope, I would like to build scope for every single test of a test suite.

Let's say we have a suite with different test classes. Assuming one test class only have 1 test method with 2 events: test starts and test finishes. I want to construct scope per test. Here is an example for two tests:

Test 1:
- create test scope
  - At test starts
  - At test finishes
- close test scope

Test 2:
- create test scope
  - At test starts
  - At test finishes
- close test scope
...
...
repeat for the rest of tests of suite

I hook those events by calling scope constructor and scope close on a test listener (a testng specific stuff).

**Comment by rbygrave** [comment]
> I would like to build scope for every single test of a test suite.

That is how it works normally now assuming I am interpreting correctly.
That is, this is how virtually all the tests in avaje-inject run now by
creating a new BeanScope for each and every test independently with
virtually all those tests doing that programmatically.

So the built in @TestScope and associated support for junit 5 is all about
the opposite of that - having the globally scoped / wired things that are
expensive (like docker containers).

But yes, we can get what you are looking for in the description above
without need for any custom scope annotation etc. Programmatically just use
try with resources like:
https://github.com/avaje/avaje-inject/blob/master/inject-test/src/test/java/org/example/coffee/fruit/AppleServiceTest.java#L40

**Comment by Travisnv** [comment]
Thanks, I did just exactly what you have in sample test class, it works. Can we back a original question: compileTestJava goal when we have:

1.custom scope interface
2. classes which is annotated with custom scope

under /src/test/java.

I have a few try moving both classes from /src/test/java to /src/main/java. At this time, both compileJava and compileJavaTest finish without any error.

**Comment by rbygrave** [comment]
Yes, I still haven't looked at that git repo yet.

**Comment by rbygrave** [comment]
It is not compiling, gives a NPE during compile
```
./gradlew --stacktrace clean test
```
```
...
Caused by: java.lang.NullPointerException
        at io.avaje.inject.generator.SimpleModuleWriter.createFileWriter(SimpleModuleWriter.java:238)
        at io.avaje.inject.generator.SimpleModuleWriter.write(SimpleModuleWriter.java:73)
        at io.avaje.inject.generator.ScopeInfo.writeModule(ScopeInfo.java:216)
        at io.avaje.inject.generator.ScopeInfo.write(ScopeInfo.java:304)
        at io.avaje.inject.generator.AllScopes$Data.write(AllScopes.java:95)
        at io.avaje.inject.generator.AllScopes.write(AllScopes.java:53)
        at io.avaje.inject.generator.Processor.process(Processor.java:71)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor.process(NonIncrementalProcessor.java:45)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        ...
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        ... 155 more
```

**Comment by rbygrave** [comment]
Ok, the problem looks like we are trying to create a custom "TestScope" plus a default scope that also gets named "TestScope" and both of these are created in the package `test`.

So for example, moving `TestClientCustomScope` into a different package to `test` say `test.foo` ... and it will work / compile.

**Comment by rbygrave** [comment]
Alternatively changing the custom scope name from `TestScope` to `MyTestScope` also works.  This is because the module name gets derived based on:
- the name of the custom annotation (for custom scopes) 
- the top level package name (for the default scope). In this case that is also `test`

... so given these 2 naming conventions both modules get called `TestScope` and both are in the same package - `test`.


Similarly if the package change from `test` then it will work.  For example changing to `testx` means one module is called `TestxModule` and the other `TestModule`.

**Comment by Travisnv** [comment]
I confirmed that both suggestion works for me. Anyway, can we add some documentation about create same name for `TestScope` around built-in annotation?

**Comment by rbygrave** [comment]
As this stage I want still treat this as a bug.  My idea at the moment is
to detect this sort of name clash and produce a hopefully good error
message.

So I am planning to keep this open until I have a crack at it. I'm pretty
confident we can detect this and do better here.


Cheers, Rob.

**Comment by rbygrave** [comment]
Ok, we now detect this module name clash case and throw a reasonable error:


> Attempting to create 2 modules both called test.TestModule. This can occur when a custom scope (named from it's annotation) has a name clash with the default module which can be named from the package. Look to resolve this by either changing the name of the custom scope annotation, or explicitly naming the default scope using @InjectModule(name), or changing the top level package used by the default scope
