### ISSUE TITLE
Private field injection

### ISSUE THREAD

**Issue by decebals** [avaje/avaje-inject#168]
I see in documentation page 
> With field injection the `@Inject` is placed on the field and the field must not be `private` and it must not be `final`.

Why this limitation? Spring and Guice allow you `@Inject` on the private field. 
It will be good for those who want to switch from Spring/Guice to Avaje, without changing the source code of the application.

**Comment by rbygrave** [comment]
> Why this limitation? 

With avaje-inject the injection is done with generated source code and as such it can not access private fields.  That is, it isn't using reflection or dynamic proxies - it's just plain old code and as such doesn't have access to private fields just like all other "normal code" that we write ourselves.


> Spring and Guice allow you @Inject on the private field.

Guice uses reflection to enable access and set private fields that way. Spring creates dynamic proxies to give it access to set private fields. 

The thinking is along the lines that we desire avaje-inject not to need reflection or dynamic proxies to do DI. If we stick to this then ALL DI can be seen as plain source code, found using an IDE, easily debugged with breakpoints etc. Plus it gives us the simplicity such that avaje-inject ends up to be a `50kb` jar and we don't incur any extra memory cost that would come with reflection.

So we aiming for fast, simple, and light.

Is reverting to use reflection (or dynamic proxies) for private field injection worth it?

**Comment by decebals** [comment]
I understand what you're saying, it makes sense.
I will modify my code (convert the access modifier injected fields).
Thanks for your work!
