### ISSUE TITLE
Interfaces with generic type parameters that extend other interfaces, don't PROVIDE those extended interfaces 

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#175]
I have a class that implements an interface `BuildTaskWithResult<Path>` which in turn inherits from `BuildTask`. However, Avaje Inject doesn't notice this and so the `@DependencyMetadata(provides)` list ends up being incomplete.

Perhaps there's an issue to do with classes that don't inherit from anything, only implement interfaces? Interfaces need to be fully walked in that situation too.

**Comment by rbygrave** [comment]
So `BuildTaskWithResult<Path> extends BuildTask` ... but the meta provides only includes `BuildTaskWithResult<Path>` and does not include `BuildTask`

Sounds like a bug there where it stops reading (inherited interfaces) after it hits the _generic type_.  I'm very sure we don't have this bug for in the non-generic case.

**Comment by rbygrave** [comment]
For example:

```java
public interface BuildTask { .. }

public interface BuildTaskWith<T> extends BuildTask { ... }

class PathBuildTask implements BuildTaskWith<Path> { ... }
```
The `PathBuildTask` should provide:  `BuildTaskWith<Path>` **_AND_** `BuildTask` ... this bug is that `BuildTask` isn't provided.

With the fix we see it is provided.  We see that in 2 places

1) `PathBuildTask$DI` `isAddBeanFor()` method includes `BuildTask.class`

```
if (builder.isAddBeanFor("path", PathBuildTask.class, BuildTask.class, TYPE_BuildTaskWithPath)) {
```

2) The associated `@DependencyMeta` ... `provides` attribute contains `BuildTask` 

```java
  @DependencyMeta(type="org.example.generic.PathBuildTask", name="path", provides={"org.example.generic.BuildTaskWith<java.nio.file.Path>","org.example.generic.BuildTask"})
  protected void build_generic_PathBuildTask_path() {
    PathBuildTask$DI.build(builder);
  }
```

**Comment by rbygrave** [comment]
version 6.19 | 5.19 on it's way to maven central with the fix  @mikehearn

**Comment by mikehearn** [comment]
Thanks again! Do you accept tips/Patreon/etc by any chance?

**Comment by rbygrave** [comment]
I do have Paypal donations on my other open source effort which is Ebean ORM :) 
https://ebean.io/sponsors

I should setup a "donate" button for these avaje libraries.

**Comment by mikehearn** [comment]
Alright well I sent you a donation via PayPal. Consider it a Christmas present and expression of my thanks for such timely and responsive maintainership. The donation is big enough that it should cover some high quality dinner dates, or a weekend break somewhere. Enjoy!

**Comment by rbygrave** [comment]
Wow, thanks @mikehearn !!  That's an awesome Xmas present. 
Cheers !!
