### ISSUE TITLE
Module interface lacks the classes() method

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#176]
I wanted to write some code that processes classes in a set of modules generically, and just discovered that classes can't be invoked through the Module interface. Looks like an oversight?

**Comment by rbygrave** [comment]
> an oversight?

Well, maybe.

The generated method is static ... `public static Class<?>[] classes()` but yes we could make it non-static and add it to the interface easily enough. The `classes()` method was generated/added to support your use case (not anyone else really) so I'm pretty sure we can just modify that method to be non-static and add it to the `Module` interface.  

The question becomes do we additionally want a static method at that point and my thought is probably not. Other people that desire a similar method that is _static_ could request that and describe why they need it to be static (but I suspect that won't happen).

**Comment by mikehearn** [comment]
Thanks. Yeah, I realize I'm using DI in slightly weird ways. If at any point my requests don't seem to have a good cost/benefit tradeoff anymore just say and I'll start maintaining features on a branch.

**Comment by rbygrave** [comment]
> using DI in slightly weird ways

Well, I'm not sure that they are weird at all.  The bits that I see looks "pretty natural" and makes good sense to me. For myself I know I have got a bit "patterned" in my thinking by my server side app bias with Spring and Guice so this has been great.  

As I see it, your questions and prompting coming from that different angle has had a massive positive impact on avaje-inject and the result feels very good and natural. Those things have meant avaje-inject has evolved into what I feel is very close to "done". 

> cost/benefit tradeoff ...  maintaining features on a branch.

Yes, all good. Generally I am not a pushover per say but as I see it you've got a really good "hit ratio" on good suggestions and issues. You haven't made me do anything I haven't wanted to :)

>  maintaining features on a branch.

I'm totally happy with forks and branching. I just want to say that I feel avaje-inject is now very very close to what I deem is it's final state in terms of feature complete.  That is, I just dropped in "AOP" support, so if I got that "right" then the only feature that I have my thoughts on adding is something to match Spring `@ConditionalOnClass` which is almost a poor mans custom scopes and I believe only relevant for use with default scope and might even be a tad "marginal".

My goal going forward is:
- Look at adding `@ConditionalOnClass`
- Exercise / use `@Aspect` more and confirm it's "done" (via resilience4j mostly)
- Bump to Java 11 & migrate from `slf4j-api` to `System.Logger`
- Be in maintenance mode

To my knowledge avaje-inject will be done with just bug fixing and maintenance at that point. As I see it, it is pretty important for avaje-inject to get to this nice stable, boring, maintenance mode state as it's often a relatively core dependency that apps rely on - we want to build our apps on solid foundations / solid core dependencies that are "done".

**Comment by mikehearn** [comment]
Great!

I may take things further and add one or two more features that I suspect I'll end up wanting. Mostly these are about allowing users to rewire objects with configuration in some ways. Right now my object graph is defined entirely in code, with objects requesting injection by type (and a bit of name based injection). The graph is actually a combination of sub-graphs that are kind of 'templated', which is what I use scopes for.

So far, so good. But actually the interface between some of the objects is rather generic. Actually they mostly just exchange the roots of file trees. A natural feature to add to my product is the ability to redirect a task object to take its input files from a different place than the outputs of the default dependency. Currently I'm not sure how best to do that with Avaje Inject. I think I'd have to find places where it makes sense to do that, and then manually write code to wire that dependency, falling back to the scope if nothing has been configured.

What I'd really like to express is something like:

`class Foo(@DefaultType(Bar::class) val inputs: GenericInterface)`

i.e. say that inputs _can_ be satisfied by anything that implements `GenericInterface`, but if nothing else exists, it should be satisfied by `Bar`. Perhaps this is what factories are for and I should just use them - at the moment I don't. The problem is that `GenericInterface` might appear in a lot of places, and the default type should be different in each place, so when the factory is asked to provide an implementation of `GenericInterface` it won't know which one to supply because it doesn't know what will be injected into.

If there's a good pattern for how to do this with the current API, I'd love to know!

**Comment by rbygrave** [comment]
> `class Foo(@DefaultType(Bar::class) val inputs: GenericInterface)`

Would one level of indirection work, along the lines of:

```
class FooInput(val fallback: Bar, val inputs: Optional<GenericInterface>)

class Foo(val inputs: FooInput)
```

**Comment by rbygrave** [comment]
>  and the default type should be different in each place

Just to say, if the above wasn't the case then we should be able to use the `@Secondary` annotation on Bar and it then becomes the "fallback" dependency.  However, as the "fallback" dependency is different in multiple injection points (it's not always just Bar) then we can't just use `@Secondary` in this manor ... unless ... (I haven't see or done this) we use qualifiers.  So like:

```
@Named("forFoo")
@Secondary
class FooFallback implements GenericInterface { }

@Named("forBazz")
@Secondary
class BazzFallback implements GenericInterface { }


class Foo(@Named("forFoo) val input: GenericInterface) { }


class Bazz(@Named("forBazz) val input: GenericInterface) { }

```

**Comment by rbygrave** [comment]
So adding a test for the above using `@Secondary`, it works IF ... the supplied instance of GenericInterface is supplied with all the qualifier names that are used like:

```java
    GenericInterface supplied = new Supplied();
    try (BeanScope beanScope = BeanScope.newBuilder()
      .withBean("forFoo", GenericInterface.class, supplied)
      .withBean("forBazz", GenericInterface.class, supplied)
      .build()) {
```

**Comment by rbygrave** [comment]
Given a "default" / "fallback" dependency 
```java
@Singleton
@Named("default")
@Secondary
public class OptDefaultBax implements OptionalService {
  @Override
  public String hi() {
    return "defaultOptionalService";
  }
}
```

We use `maybeService.orElse(fallback)` like: 

```java
@Singleton
public class OptBax {

  final OptionalService service;

  public OptBax(OptDefaultBax fallback, Optional<OptionalService> maybeService) {
    this.service = maybeService.orElse(fallback);
  }

}
```

Noting that we need `@Named("default")` with the `@Secondary` such that it is added/wired even when an instance of OptionalService is supplied to the bean scope.

**Comment by mikehearn** [comment]
Hmm. OK, so it's possible, but does require code at every use site, and duplicating some stuff in annotations.

I might look into what it takes to be able to wire a class A specifically to another class B in the BeanScope, rather than have it be figured out just based on target type.
