### ISSUE TITLE
List of implementing interfaces with generics - "No dependency provided" when injecting List or Set

### ISSUE THREAD

**Issue by doppelrittberger** [avaje/avaje-inject#179]
Hi,

I use @Inject in combination with a ``List<MyInterface<Type>>`` to inject all implementors of this interface. Avaje seems to ignore the generics and fails to compile with "No dependency provided". 

If a PR is ok please let me know.

Thanks
Markus

**Comment by rbygrave** [comment]
Yes, a PR would be great.
