### ISSUE TITLE
Static inner classes as dependencies

### ISSUE THREAD

**Issue by doppelrittberger** [avaje/avaje-inject#180]
Hi,

if I use static inner classes as bean definitions Avaje seems to struggle. It creates a package which is named like the parent class and this package clashes with the parent class itself.
```
public class MyBeans {
@Singleton
public static class Bean1 {}
}
```
Above example generates a class in package ``MyBeans`` and this name clashes with the name of the class ``MyBeans``.

If a PR is ok please let me know.

Thanks
Markus

**Comment by rbygrave** [comment]
Yes, a PR would be great !!

**Comment by rbygrave** [comment]
Fix PR merged into master, closing.
