### ISSUE TITLE
Website claims latest version is 6.11

### ISSUE THREAD

**Issue by mikehearn** [avaje/avaje-inject#184]
Would be good to update it!

**Comment by rbygrave** [comment]
Done, bumped to 6.20 which is latest.

Noting that ideally I think the docs needs some tutorial style documentation:
- Basic injection
- Using `@Factory` / `@Bean`
- Using `@TestScope`
- Using custom scopes
- Using AOP Aspects

... and ideally we get more people kicking the tires.
