### ISSUE TITLE
Dependencies [javax.sql.DataSource] are not provided - missing @Singleton, @Component, @Factory/@Bean or specify external dependency via @InjectModule requires attribute

### ISSUE THREAD

**Issue by kevin70** [avaje/avaje-inject#217]
version: 8.4

```
No dependency provided for javax.sql.DataSource on org.jdbi.v3.core.Jdbi
Dependencies [javax.sql.DataSource] are not provided - missing @Singleton, @Component, @Factory/@Bean or specify external dependency via @InjectModule requires attribute
```

code:
```
  @Bean(destroyMethod = "close")
  public HikariDataSource dataSource() {
    var c = config.getConfig("jdbc.ds");
    var hc = new HikariConfig();
    hc.setJdbcUrl(c.getString("jdbc-url"));
    hc.setUsername(c.getString("username"));
    hc.setPassword(c.getString("password"));
    hc.setDriverClassName(c.getString("driver-class-name"));
    hc.setMinimumIdle(c.getInt("min-idle"));
    hc.setMaximumPoolSize(c.getInt("max-pool-size"));
    hc.setConnectionTestQuery(c.getString("connection-test-query"));
    hc.setAutoCommit(false);
    return new HikariDataSource(hc);
  }
```
hello.
I need to register the data source and expect to automatically call the destruction function when the application stops.

However, the 'DataSource' interface has no destruction function, so I need to return the 'HikariDataSource' type here. However, functions that depend on 'DataSource' cannot use the interface type, and 'HikariDataSource' injection must also be adopted.

**Comment by rbygrave** [comment]
Can you show the generated code that registers the `HikariDataSource` ... the generated method with the 
`if (builder.isAddBeanFor(HikariDataSource.class, ...)) {`

Can you show us that? What we see here are the name and types that the HikariDataSource bean is going to be registered for. We are looking to see if `javax.sql.DataSource` is there.

**Comment by kevin70** [comment]
```
/**
 * Generated source - dependency injection builder for DbBeans.
 */
@Generated("io.avaje.inject.generator")
public class DbBeans$DI  {

  /**
   * Create and register HikariDataSource via factory bean method DbBeans#dataSource().
   */
  public static void build_dataSource(Builder builder) {
    if (builder.isAddBeanFor(HikariDataSource.class, HikariConfig.class, DataSource.class, CommonDataSource.class, Wrapper.class, HikariConfigMXBean.class)) {
      DbBeans factory = builder.get(DbBeans.class);
      HikariDataSource bean = factory.dataSource();
      HikariDataSource $bean = builder.register(bean);
      builder.addPreDestroy($bean::close);
    }
  }
}
```

**Comment by rbygrave** [comment]
Ok cool. I'm pretty sure I can reproduce the issue.

The meta data does not have "provides javax.sql.DataSource".  So the ordering of wiring isn't correct which gives us this error.  So I need to check if/why bean factory method isn't giving us the "provides" we expect in the meta data (which is used to control wiring order).

**Comment by rbygrave** [comment]
I have reproduced and have a fix.  

In summary all the factory beans prior to this fix have missing / empty `provides` ... I'm not sure how we didn't hit this before really. Anyway, pushing the failing test and fix into a branch.
