### ISSUE TITLE
Add documentation for `@Prototype`, AOP Aspects, and why we don't have - "lazy singletons", @Value, "refreshable context"

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-inject#223]
Documentation that still is missing:

    @Prototype
    AOP Aspects

Plus [design] documentation for, Why avaje-inject does not have ...

    Does not have "lazy singleton"
    Does not have @Value (why we expect to do external configuration differently including dynamic configuration)
    Does not have "refreshable context"

**Comment by SentryMan** [comment]
I'd gladly add the Prototype/AOP stuff, but I'm in a chicken-and-egg situation since I have no idea what this lib does with them. (Because of the lack of docs.)

**Comment by rbygrave** [comment]
Yup, cool.  Examples in the tests if you are interested.

**Comment by SentryMan** [comment]
So what's the deal with lazy singletons? Can't write your reasons if I don't know them.

**Comment by SentryMan** [comment]
so like do we count this as resolved or what?

**Comment by rbygrave** [comment]
Yeah, lets close this off now.
