### ISSUE TITLE
Awesome Java Annotation Processing curated list

### ISSUE THREAD

**Issue by natros** [avaje/avaje-inject#232]
Hi,

May I suggest you register this project on the Awesome Java Annotation Processing curated list for this project to gain more visibility

https://github.com/gunnarmorling/awesome-annotation-processing

Thanks.

**Comment by rbygrave** [comment]
Yeah cool, done.  

In case you didn't know I have a few other annotation processors.
- [avaje-jsonb](https://github.com/avaje/avaje-jsonb) - json mapping as source code generation
- [avaje-http-client-generator](https://avaje.io/http-client/start#api-start) - http client generation similar to retrofit but uses JDK HttpClient
- [avaje-http](https://avaje.io/http/) - rest server generation similar to jax-rs targeting Javalin, Helidon and avaje-jex
- [ebean querybean generator](https://ebean.io/docs/query/query-beans) Ebean ORM query bean generator for strongly typed Ebean ORM queries

In terms of Http Json Rest servers, I understand the Helidon project is creating a new loom friendly http server. When that is available I will add support to that via avaje-jex which is a web routing layer (lighter java only variation from Javalin).

**Comment by natros** [comment]
Certainly. I'm exploring new integration ideas. And I come from jetty, guice, resteasy and dagger and I see your project as a good opportunity to use avaje-inject with helidon-se and embrace the latest versions of java.

Thank you for this wonderful piece of software.

**Comment by rbygrave** [comment]
I think we can close this now.
