### ISSUE TITLE
Support factory with qualifiers

### ISSUE THREAD

**Issue by natros** [avaje/avaje-inject#234]
I have a `BlueBean` and `RedBean`
```java
public interface MyBean {}
public class BlueBean implements MyBean {
  @Override
  public String toString() {
    return "blue";
  }
}
public class RedBean implements MyBean {
  @Override
  public String toString() {
    return "read";
  }
}
```
and a factory to create the beans with a qualifier `@Blue` and `@Red`
```java
@Factory
public class MyFactory {
  @Bean
  @Blue
  MyBean blueBean() {
    return new BlueBean();
  }

  @Bean
  @Red
  MyBean redBean() {
    return new RedBean();
  }
}
``` 

when running `MyFactoryDemo` i'm getting the same bean.

```java
@Singleton
public class MyFactoryDemo {
  @Inject
  MyFactoryDemo(@Blue MyBean blueBean, @Red MyBean redBean) {
    System.out.printf("blue=%s, red=%s\n", blueBean, redBean);
  }

  public static void main(String[] args) {
    try (BeanScope ctx = BeanScope.builder().build()) {
      ctx.get(MyFactoryDemo.class);
    }
  }
}
```

The only way to work if using `@Named("blue")` instead of `@Blue`

**Comment by rbygrave** [comment]
Looks at the tests ... dang, none of them have this case, and yes this bug reproduces.

FYI: 
```java
  //@Frodo
  @Named("frodo")
  @Bean
  Que frodoQueue() {
    return new BasicQue("frodo");
  }
```
Looking at the generated code that calls this method we see the `isAddBeanFor()` with the `"frodo"` qualifier.
```java
  public static void build_frodoQueue(Builder builder) {
    if (builder.isAddBeanFor("frodo", Que.class)) {
      ...
    }
  }
```
Changing to use `@Frodo`  from `@Named("frodo")` ... and we see that the qualifier name is no longer there:
```java
  public static void build_frodoQueue(Builder builder) {
    if (builder.isAddBeanFor(Que.class)) { // Qualifier is missing here
      ...
    }
  }
```
That is, the `isAddBeanFor()` shows us the **_qualifier name_** and **_types_** this bean is going to be registered for (and hence what avaje-inject should be able to inject it into).
