### ISSUE TITLE
It's not possible to inject BeanScope

### ISSUE THREAD

**Issue by natros** [avaje/avaje-inject#235]
Micronaut allows to inject `BeanContext` and `ApplicationContext`. Guice can inject `Injector`.

My use case is that I'm trying to convert this code that uses guice to avaje-inject

```java
// quartz job factory
class GuiceJobFactory implements JobFactory {
  private final Injector injector;

  @Inject
  GuiceJobFactory(Injector injector) {
    this.injector = injector;
  }

  @Override
  public Job newJob(TriggerFiredBundle bundle, Scheduler scheduler) {
    Class<? extends Job> cls = bundle.getJobDetail().getJobClass();
    return injector.getInstance(cls);
  }
}
```

Thanks

**Comment by rbygrave** [comment]
> Micronaut allows to inject BeanContext and ApplicationContext. Guice can inject Injector.

Oh wow, I didn't know that.  Nice use case - dynamically obtain the job to run - got it.

I'll have a look and see how we can inject `BeanScope` to get the same effect.

**Comment by xabolcs** [comment]
Hi @natros , would you mind putting here that job factory snippet again, but now in the aveje-inject form?
Thanks!

**Comment by SentryMan** [comment]
```
@Singleton
class AvajeJobFactory implements JobFactory {
 
	private final BeanScope scope;

  AvajeJobFactory(BeanScope scope) {
    this.scope = scope;
  }

  @Override
  public Job newJob(TriggerFiredBundle bundle, Scheduler scheduler) {
    Class<? extends Job> cls = bundle.getJobDetail().getJobClass();
    return scope.get(cls);
  }
}

```
