### ISSUE TITLE
ENH: Simplify multi-module compilation and wiring but auto detecting provides and requires

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-inject#262]
Add to Module:
- `autoProvides()` as the types this module will provide. (Initially restricted to top level provided interfaces)
- `autoProvidesAspects()` as the aspects this module will provide
- `autoRequires()` as the types this module requires when wiring that are not provided locally but are provided by another module that is in the classpath at the time of compilation

Currently this all needs to be done manually via `@InjectModule(provides=... ,  requires=...)`.  Conceptually with these autoProvides and autoRequires this can be determined at compile time.

**Comment by rbygrave** [comment]
Works well on the modular coffee maker example - works without any explicit requires/provides with the autoProvides and autoRequires doing the right thing. I think this is good.

**Comment by SentryMan** [comment]
> Works well on the modular coffee maker example - works without any explicit requires/provides with the autoProvides and autoRequires doing the right thing. I think this is good.

got a link?

**Comment by rbygrave** [comment]
https://github.com/dinject/examples/tree/master/modular-coffee-app
