### ISSUE TITLE
Can this be used in GraalVM native image?

### ISSUE THREAD

**Issue by wasifaleem** [avaje/avaje-inject#266]
Looks like using avaje-inject breaks native image builds. After incorporating the library and constructing the bean scope my cli app native image builds gets stuck. I verified that the build works without using this library. 

This might be a limitation of GraalVM native images, but has anyone encountered this before?

Gradle plugin Config:
```
id("org.graalvm.buildtools.native") version "0.9.19"

graalvmNative {
    binaries {
        named("main") {
            javaLauncher.set(javaToolchains.launcherFor {
                languageVersion.set(JavaLanguageVersion.of(19))
                vendor.set(JvmVendorSpec.matching("GraalVM Community"))
            })
            metadataRepository {
                enabled.set(true)
            }

            imageName.set("xxx")
            mainClass.set("xx.xxx")
            requiredVersion.set("22.3")
        }
    }
}
```

Versions
1. avaje-inject: 8.11
2. JDK
```
  ~ java -version
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08)

```

**Comment by SentryMan** [comment]
Yes, it can, I've used it with GraalVM before. Can you give a full stack trace?
