### ISSUE TITLE
Parent with wildcard results in compile failure

### ISSUE THREAD

**Issue by Tim203** [avaje/avaje-inject#283]
I was just checking out this repository to see whether it could replace my Guice usage.
I however ran into an issue where Avaje Inject produced invalid code for one specific class.
I've stripped out pretty much everything except what's needed to reproduce this error.

Since it's basically nothing I'll post it here:
```java
public interface Subscriber<E> {
}

public interface EventBus<E, S extends Subscriber<? extends E>> {
}

@Singleton
public class EventBusImpl implements EventBus<Object, Subscriber<?>> {
}
```

It creates the following invalid code:
```java
public final class EventBusImpl$DI  {

  public static final Type TYPE_EventBusObjectSubscriber? = new GenericType<*package*.EventBus<java.lang.Object,*package*.Subscriber<?>>>(){}.type();

  /**
   * Create and register EventBusImpl.
   */
  public static void build(Builder builder) {
    if (builder.isAddBeanFor(EventBusImpl.class, TYPE_EventBusObjectSubscriber?)) {
      var bean = new EventBusImpl();
      builder.register(bean);
    }
  }

}
```
Which is invalid because `?` is an operator.

**Comment by SentryMan** [comment]
Nice catch, I'll look into it.

**Comment by SentryMan** [comment]
should be fixed in the next release/RC candidate.

**Comment by Tim203** [comment]
That was quick, thanks!
