### ISSUE TITLE
java.lang.NoClassDefFoundError: io/swagger/v3/oas/annotations/security/SecurityRequirement

### ISSUE THREAD

**Issue by kevin70** [avaje/avaje-inject#285]
stacktrace:
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/swagger/v3/oas/annotations/security/SecurityRequirement
	at cool.houge.wuneng.controller.RoleController$DI.build(RoleController$DI.java:21)
	at cool.houge.wuneng.WunengModule.build_controller_RoleController(WunengModule.java:241)
	at cool.houge.wuneng.WunengModule.build(WunengModule.java:161)
	at io.avaje.inject.DBeanScopeBuilder.build(DBeanScopeBuilder.java:170)
	at cool.houge.wuneng.main.Application.run(Application.java:64)
	at cool.houge.wuneng.main.Application.main(Application.java:54)
Caused by: java.lang.ClassNotFoundException: io.swagger.v3.oas.annotations.security.SecurityRequirement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
Caused by: java.lang.ClassNotFoundException: io.swagger.v3.oas.annotations.security.SecurityRequirement

	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```

controller:
```
@Path("/s/roles")
@Controller
@SecurityRequirement(name = "JWT")
public class RoleController {
  // ...
}
```

source:
```
@Generated("io.avaje.inject.generator")
public final class RoleController$DI  {

  /**
   * Create and register RoleController.
   */
  public static void build(Builder builder) {
    if (builder.isAddBeanFor(RoleController.class, Controller.class, SecurityRequirement.class)) {
      var bean = new RoleController();
      var $bean = builder.register(bean);
      builder.addInjector(b -> {
        // field and method injection
        $bean.roleService = b.get(RoleService.class);
        $bean.beanMapper = b.get(VoBeanMapper.class);
      });
    }
  }

}
```

I expect swagger-annotations to be used only at compile time. Can you specify to remove certain dependencies that are not needed at run time?

**Comment by SentryMan** [comment]
What does the role controller look like? give me a general idea.

**Comment by rbygrave** [comment]
> Can you specify to remove certain dependencies 

`SecurityRequirement` isn't a dependency per say but an annotation. What avaje-inject is doing currently is that is registering the beans **_also by annotation_** (in addition to the expected interfaces and classes).

The first question is:  
**_Q: Was it ever a good idea to register the beans by their annotations?_**

For myself I'm having doubts that this was ever a good idea. Its that feature where you ask what use cases this is required for? When do people want to get all the beans that have a given annotation?

I believe the original thinking was that I didn't see a use case for it but I didn't see harm in doing it. So right now we see some pain from this behavior but I don't think it is actually useful and provides value.

With that thinking, the "fix" is to not actually register beans by their annotations. This is the change we should do unless there is a really good use for "get all the beans by annotation" but even then this seems to me today like a problematic feature going forward. 

The alternative or additional feature is to support a blacklist or whitelist mechanism to control the types that the bean is registered against _but_ ... my gut says to not register beans by their annotations. 

My thought is to release 8.13-RC1 off master now, and then see what "not registering beans by their annotations" looks like.

**Comment by rbygrave** [comment]
> release 8.13-RC1 off master now

FYI: Not sure that release was successful.  maven central staging for the s01 instance we use had a bad day yesterday and looks like that is still ongoing.

**Comment by Tim203** [comment]
Maybe an annotation can be added that annotations should use when they want all usages to be registered?
I for example would like to have a list of all classes that have the `@Listener` annotation, but I don't need to see a list of all classes that have `@SupressWarnings`.

**Comment by rbygrave** [comment]
> would like to have a list of all classes that have the @Listener annotation

**_like_** to or really **_need_** to ?  

What is the use for ... 'all classes that have the `@Listener` annotation' ?

**Comment by SentryMan** [comment]
You also get the list back as an List<Object> which isn't super useful compared to just using an interface.

**Comment by Tim203** [comment]
> **_like_** to or really **_need_** to ?
> 
> What is the use for ... 'all classes that have the `@Listener` annotation' ?

Like. I could make an empty interface but at that point I prefer an annotation.

> You also get the list back as a `List<Object>` which isn't super useful compared to just using an interface.

That's fine for what I'm planning to do with it.
I currently use Guice and Guice has `bindListener` which notifies the listener for all the injectable matches (in my case when it finds a class with the annotation `@Listener`) and I use that to register all those objects (after they've been injected) to the EventBus.

A listener class looks quite a lot like what you guys have with avaje-http's Controllers:
```java
@Controller
public class ArtistController {
  @Get
  Artist getAll() {
    ...
  }
}
```
Where Controller would be replaced with Listener and Get with Subscribe.
The event library takes care of finding the events of a listener, but let me know if there are better ways to do this with avaje-inject.

**Comment by SentryMan** [comment]
> let me know if there are better ways to do this with avaje-inject.

If the listener/subscribe annotations are nothing but marker annotations, my initial thought would be to have an interface like this. 

```java
interface Listener {

  T subscribe();
}
```
and just have your classes extend it. 

with that, you could directly inject the listeners into your event bus class (you currently cannot directly inject by annotation)

```java
public class EventBus {

 public EventBus(List<Listener> listymclistface) {
    //do whatever with the listeners
  }
}
```

**Comment by rbygrave** [comment]
I'm just noting that we could support listByAnnotation() by just streaming through all the "bean entries" and filtering them like: 
```java
  public List<Object> listByAnnotation(Class<? extends Annotation> annotation) {
    return all().stream()
      .filter(entry -> entry.type().isAnnotationPresent(annotation))
      .collect(Collectors.toList());

    // TODO: include parent scope as well ...
``` 

... so do this at runtime rather than inject time (allowing avaje-inject to remove the registration by annotations at inject time).


---------

>  have an interface ... directly inject the listeners into your event bus class

This would be my thinking too ... so I'm guessing EventBus might be a 3rd party library that uses a bit of reflection. 

> Guice has bindListener which notifies the listener for all the injectable matches (in my case when it finds a class with the annotation `@Listener`) and I use that to register all those objects (after they've been injected) to the EventBus.

If you can share some of the bindListener being used that would be interesting. It sounds like EventBus works via reflection but it would be good to understand how this works with guice bindListener currently.

**Comment by rbygrave** [comment]
The fix  has been released in **8.13-RC2** and that is now in maven central so you can try that out if you like. When using that version annotations on the bean are no longer registered - we won't see `SecurityRequirement.class` in the generated `isAddFor()`.

**Comment by Tim203** [comment]
> If you can share some of the bindListener being used that would be interesting.

https://github.com/GeyserMC/Floodgate/blob/dd37174ad3e89b3da21e3599b28bfe1cc3b4dd17/core/src/main/java/org/geysermc/floodgate/module/CommonModule.java#L84-L89

Example listener class: https://github.com/GeyserMC/Floodgate/blob/dd37174ad3e89b3da21e3599b28bfe1cc3b4dd17/core/src/main/java/org/geysermc/floodgate/skin/SkinUploadManager.java

>  It sounds like EventBus works via reflection

It does use Reflection. However, if it's not a lot of work, I'd be interested in moving that to compile time.

**Comment by SentryMan** [comment]
With 0 context, I'd go with the interface approach and directly wire the Listeners into the EventBus via a constructor/method. The question I have is whether the Listener/Subscribe annotations have some other functionality than just marking the class/method.
