### ISSUE TITLE
Can we make the AOP Proxy Classes not catch all Throwable?

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-inject#341]
It's kind of a hassle to constantly catch and unwrap the Invocation Exception to rethrow the Runtime exception I'm expecting.

**Comment by rbygrave** [comment]
Can you provide an example / context for this question. We need to handled checked exceptions etc so perhaps include an example of what is generated for an given method signature and then maybe it is more obvious why it's an issue?

Cheers, Rob.

**Comment by SentryMan** [comment]
Say I got an aspect called `ScopedValueMDC` if I place it on an HTTP client method, they will no longer throw the expected `HttpException` on 5xx errors since that is wrapped inside of an invocation exception.  

```
@Singleton
@Client
public interface ApiClient {

  @Get
  @ScopedValueMDC("funny picture")
  HttpResponse<InputStream> call(@Header("Accept") String accept);
}
```
Now I need more logic to extract the HttpException.

```
    try {
      final Sus github;
      final var contributors = github.contributors("rbygrave", "junk");

    } catch (final InvocationException iex) {
      if (iex.getCause() instanceof final HttpException ex) {
        if (ex.getCause() != null) {
          // some IO/Interrupted exception happened while sending request.
        } else {
          // Use HttpException utility methods to access response status and handle/deserialize
          // error body
        }
      }
    }
```

**Comment by SentryMan** [comment]
Perhaps we could do an instance of check in the generated proxy method and simply rethrow the checked exception?
```java
@Singleton
@Client
public interface ApiClient {

  @Get
  @ScopedValueMDC("funny picture")
  HttpResponse<InputStream> call() throws CheckedException;
}
```
we would have the proxy method throw the same checked exception
```java
  @Override
  public java.net.http.HttpResponse<java.io.InputStream> call() throws CheckedException {
    var call = new Invocation.Run<>(() -> super.call(accept))
      .with(this, call0, accept);
    try {
      call0Timed.invoke(call);
      return call.finalResult();
    } catch (InvocationException e) {
      throw e;
    } catch (Throwable e) {
 
      if(e instanceof RuntimeException ex) throw ex;
      else if (e instanceof CheckedException ex) throw ex;
      else throw new InvocationException(e);
    }
  }
```

**Comment by SentryMan** [comment]
Ah, I just noticed that this behavior is there when you explicitly add `throws` to the method signature. It generates like this:
```
  @Override
  public java.net.http.HttpResponse<java.io.InputStream> call() throws CheckedException {
    var call = new Invocation.Run<>(() -> super.call())
      .with(this, call0, accept);
    try {
      call0Timed.invoke(call);
      return call.finalResult();
    } catch (InvocationException | CheckedException e) {
      throw e;
    } catch (Throwable e) {
       throw new InvocationException(e);
    }
  }
```
when I modify a method signature with throws

**Comment by SentryMan** [comment]
Can we just add a catch clause for rethrowing runtime exceptions?

**Comment by rbygrave** [comment]
So currently the generated code is:

```java
    ...
    } catch (InvocationException | CheckedException e) {
      throw e;
   ...
```

And we instead like it to include RuntimeException like:
```java
    ...
    } catch (RuntimeException | InvocationException | CheckedException e) {
      throw e;
   ...
```

And the reason for this is .... when the client api method throws a RuntimeException it is currently wrapped as an `InvocationException ` and this is a pain because ...[some reason].


Noting that when the client api does not throw a CheckedException we want to generate similar code but it just does not include the CheckedException.


Is that correct?

**Comment by SentryMan** [comment]
Basically yeah

**Comment by SentryMan** [comment]
oh yeah, looks like there is a bug with this. when the method sig throws `Exception` it fails to compile because.

```java
    ...
    } catch (InvocationException | Exception e) {
      throw e;
   ...
```
is invalid.

**Comment by rbygrave** [comment]
To kind of state the obvious, `InvocationException` is a `RuntimeException` ... so we could **_almost_** swap out `InvocationException` with `RuntimeException` here in this catch block except for detected bugs where the method throws Exception (or Throwable) in which case we need to suppress catching the RuntimeException.
