### ISSUE TITLE
Generic type not generating correctly on second implementation

### ISSUE THREAD

**Issue by literallyEllie** [avaje/avaje-inject#347]
Hello, I have a little issue with the code generation for a generic type. this probably isn't a great description so here is an example

This is my project structure (grade): 
```
datasource:
 \_ common
    - public interface Repository<T, M> 
 \_ mongodb 
   - public abstract class MongoRepository<T> implements Repository<T, Document>
...

player-service
\_ server
    - public class PlayerMetaRepository extends MongoRepository<MetaEntry> { 
```

On compilation of player-service there is a syntax error with the PlayerMetaRepository$DI.

```
@Generated("io.avaje.inject.generator")
public final class PlayerMetaRepository$DI  {

 // error is here at "T"
  public static final Type TYPE_RepositoryTDocument = new GenericType<package.datasources.Repository<T,org.bson.Document>>(){}.type();

  /**
   * Create and register PlayerMetaRepository.
   */
  public static void build(Builder builder) {
    if (builder.isAddBeanFor("playermeta", PlayerMetaRepository.class, MongoRepository.class, TYPE_RepositoryTDocument)) {
      var bean = new PlayerMetaRepository(builder.get(MongoDBDatasource.class,"!datasource"));
      builder.register(bean);
    }
  }
}
```

Error:
```
error: cannot find symbol  
public static final Type TYPE_RepositoryTDocument = new GenericType<package.datasources.Repository<T,org.bson.Document>>(){}.type();
                                                                                                        ^
  symbol:   class T
  location: class PlayerMetaRepository$DI
```
It is referencing `Repository` instead of its implementation `MongoRepository`, and then the T is not being accounted for D:

Thank you for your time 🍎

**Comment by SentryMan** [comment]
can you show how you are injecting the repository into `PlayerMetaRepository`?

**Comment by LoonyRules** [comment]
Slightly unrelated to the generic type problem here, but wouldn’t this also cause the end user a problem if they tried to extend MongoRepository and Repository more than once, due to the $DI builder checking to add a bean for all of the super class types?

**Comment by literallyEllie** [comment]
> can you show how you are injecting the repository into `PlayerMetaRepository`? Like what does the constructor look like?

```
@Singleton
@InjectModule(requires = MongoDBDatasource.class)
public class PlayerMetaRepository extends MongoRepository<MetaEntry> {
    [..]

    @Inject
    public PlayerMetaRepository(MongoDBDatasource datasource) {
        super(datasource);
    }
```

here you go 🕺

**Comment by SentryMan** [comment]
> Slightly unrelated to the generic type problem here, but wouldn’t this also cause the end user a problem if they tried to extend MongoRepository and Repository more than once, due to the $DI builder checking to add a bean for all of the super class types?

```java
 if (builder.isAddBeanFor("playermeta", PlayerMetaRepository.class, MongoRepository.class, TYPE_RepositoryTDocument)) 
```
As I understand it, this line checks that a bean that satisfies all these conditions hasn't been set. It will wire if there isn't an existing PlayerMetaRepository bean.

> here you go 🕺

Thanks, I can replicate the issue and work on a fix.

**Comment by rbygrave** [comment]
Excellent work everybody and thanks @SentryMan for providing a fix for this issue (which is merged into master).

## Notes:

When we look at the code that was being generated there was really 2 bugs / issue with it.

```java
builder.isAddBeanFor("playermeta", PlayerMetaRepository.class, MongoRepository.class, TYPE_RepositoryTDocument)
```

It was registering `MongoRepository.class` but that was a generic type and should not have been registered like that. That is , the 2 issues with that generated code were:

1. It didn't compile due to the generic `T` type (ideally should have been MetaEntry)
2. The MongoRepository should have been registered as a generic type - `MongoRepository<MetaEntry>`


In terms of the failing test code (which uses slightly different names but hopefully you can follow it) ...

For the failing test case, the broken generated code was:
```java
  public static final Type TYPE_ARepoTMoDocument = new GenericType<org.example.myapp.i347.ARepo<T,org.example.myapp.i347.MoDocument>>(){}.type();

  /**
   * Create and register MyMetaDataRepo.
   */
  public static void build(Builder builder) {
    if (builder.isAddBeanFor(MyMetaDataRepo.class, MyMongoRepo.class, TYPE_ARepoTMoDocument)) {
      var bean = new MyMetaDataRepo();
      builder.register(bean);
    }
  }
```

And the fixed generated code is now:

```java
  public static final Type TYPE_MyMongoRepoMyMetaData = new GenericType<org.example.myapp.i347.MyMongoRepo<org.example.myapp.i347.MyMetaData>>(){}.type();

  /**
   * Create and register MyMetaDataRepo.
   */
  public static void build(Builder builder) {
    if (builder.isAddBeanFor(MyMetaDataRepo.class, TYPE_MyMongoRepoMyMetaData, ARepo.class)) {
      var bean = new MyMetaDataRepo();
      builder.register(bean);
    }
  }
```

The 2nd issue is now fixed as we see the `TYPE_MyMongoRepoMyMetaData`. 

For the 1st issue, we've lost the generic type info and it's registering as `ARepo.class` rather than the ideal which would be the type that represents the generic `ARepo<MetaEntry,MoDocument>`.

**Comment by rbygrave** [comment]
@literallyEllie  avaje-inject version `9.2` has just been released to maven central. You should be able to try that shortly and confirm that fixes the issue.

People can post questions here if something about this issue that isn't clear enough etc.  Thanks again @SentryMan for the fix.

Cheers, Rob.

**Comment by literallyEllie** [comment]
Hi, yes I can confirm that fixes the issue, thank you all! 😄
