### ISSUE TITLE
Module Debug Logging

### ISSUE THREAD

**Issue by Mechite** [avaje/avaje-inject#373]
Continuation of https://github.com/avaje/avaje-inject/pull/370 - This issue could be migrated to applog if it is suitable.

**Comment by SentryMan** [comment]
So I'm still a bit fuzzy on the solution.

> But ... that could be accounted for I think by just adding an IF block - hmm, interesting thought ...

What are we thinking here?

**Comment by rob-bygrave** [comment]
> What are we thinking here?

The ideal is that slf4j merges that PR and includes that fix. 

- IMO there is going to be a lot of confusion across the Java community if slf4j doesn't merge that and sticks with the incorrect format. 
- AppLog could include a wrapper that formats both ways but ... that dependency would need to be upgraded in a LOT of places so I don't really want to do that.

So currently I hope sljf4 merges that PR in some reasonable timeframe and in the meantime we have a couple of ways of working around it.

So currently it depends on if and when Ceki responds really. Give it a week and see basically.

**Comment by Mechite** [comment]
Awesome! This issue can be closed after the next release is out (`2.0.8`) - the below badge will show 2.0.8 when it has released
![slf4j-jdk-platform-logging version display](https://img.shields.io/maven-central/v/org.slf4j/slf4j-jdk-platform-logging)

**Comment by rbygrave** [comment]
We can close this now with `v2.0.9` out.
