### ISSUE TITLE
Module-Info Validation

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-inject#389]
I just had a brainwave, what if we read a project's module-info at compile time to validate that the project modules have the correct `provides Module` directive for the generated module? In this way, it would be impossible to forget to add the necessary `provides` statement. 

We can probably get the ModuleElement and read it by going up the enclosed elements of a bean.

**Comment by rbygrave** [comment]
Sounds good !!

**Comment by SentryMan** [comment]
I appear to have slammed into a wall, the `provides` statements don't show up for generated classes.

**Comment by SentryMan** [comment]
In fact, merely calling `module.getDirectives()` will guarantee compilation fails for some reason. (the classes generate, but module-info will suddenly fail to compile)
