### ISSUE TITLE
@Component.Import for classes with package private constructors

### ISSUE THREAD

**Issue by harrel56** [avaje/avaje-inject#396]
Hello there, I just recently started playing with avaje libs on my side project, but I'm struggling with one thing.
I have a dependency which has classes annotated with `@Singleton`, `@Inject` and so on, and I want to register few of them in my bean scope. I guess the correct way to do it is by using `@Component.Import`? It seems to do exactly what I want but the issue is that the constructors in these classes have package private access and oddly enough avaje generates sources for them in different package.

Did a quick research because all components from my project are generated in a correct package - and it turns out that since version `9.3` the package for imported components is appended with `.di`. Am I missing something? Is there a way to get it working with the newest version of avaje?

Hopefully my use case is clear, but if not - I can elaborate more. Thanks in advance!

**Comment by SentryMan** [comment]
We changed it because on the module system two modules cannot have the same package. I can look at making a flag to enable the old behavior if you really need it.

**Comment by harrel56** [comment]
I feel like making injectable constructors package-private is rather a common practice, so I would suspect that more people could stumble upon this issue. And it would be a real pain to not have any possibility to make it work.

I see that you have already created PR for that - really appreciate it :) suggested approach looks sufficient

**Comment by SentryMan** [comment]
Is it? I've usually seen bean constructors be public.

**Comment by harrel56** [comment]
Hmm, I've seen this approach in some projects, but they were not really intended to be consumed as external dependencies, so maybe it won't be as common issue as I thought

**Comment by rbygrave** [comment]
> constructors in these classes have package private access

As I see it, package private should be the default for constructors of components. They only need to be accessible for DI and testing and should not need to be public.

**Comment by rbygrave** [comment]
This fix is released in version `9.6-RC1`so you can try that out in about 20 minutes (time to get into maven central).

Note that with this fix it should detect if the constructor on the imported component is public or not, and only use the sub-package when the constructor is public.

**Comment by harrel56** [comment]
Thanks! Hopefully gonna try that out later today

**Comment by harrel56** [comment]
Hmm, actually I would need a version variant for `javax` to test it out - so not gonna give feedback here. Gonna wait for full release with javax and then update

**Comment by SentryMan** [comment]
interesting, is there a reason you don't use jakarta?

**Comment by harrel56** [comment]
Yes, the external library uses it

**Comment by SentryMan** [comment]
You can import any class, not only those that have a singleton animation.

**Comment by SentryMan** [comment]
ah but hmm, if you require the javax dependency for other things I suppose it makes sense
