### ISSUE TITLE
Add a mechanism to determine multi-module wiring order at compile time. (for multi-module projects)

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-inject#478]
Currently, bean DI classes are created and their dependencies validated at compile time, but determining the wiring order of multi module projects is still performed at runtime. I think we should move this determination to the compile phase.

**Comment by rbygrave** [comment]
I think we need to improve the description of this issue because it reads like the bean wiring order is determined at runtime which isn't true [at that is confusing].

This issue is about module wiring order only.

**Comment by SentryMan** [comment]
changed, but do you think it is a worthy Idea?
