### ISSUE TITLE
Lombok Constructors supported?

### ISSUE THREAD

**Issue by soenkekrusche** [avaje/avaje-inject#500]
I just found out about avaje and have been playing around a bit.
When I tried to use Lombok @RequiredArgsConstructor it resulted in a compiler error.

Consulting the documentation or github issues was not helpful yet, as lombok is not mentioned anywhere.

Is there something I fundamentally understood wrong or forgot?

```
@AllArgsConstructor
@Singleton
public class Service {

    private final Repository repository;

    public String stuff() {
        return repository.foo();
    }
}
```

will produce
 `java: constructor Service in class org.example.Service cannot be applied to given types;
  required: org.example.Repository
  found:    no arguments
  reason: actual and formal argument lists differ in length` - but writing the constructor by hand works

**Comment by SentryMan** [comment]
hmm how interesting

it seems you'll need to add the lombok dependency above the generator dependency in your pom. The reason is lombok needs to run before avaje or else the constructors won't be detected (because they don't exist when avaje is looking at your class)

this won't work:
```xml
<dependency>
    <groupId>io.avaje</groupId>
    <artifactId>avaje-inject-generator</artifactId>
    <version>${avaje.inject.version}</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.30</version>
    <scope>provided</scope>
</dependency>
```

while this does 

```xml
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.30</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>io.avaje</groupId>
    <artifactId>avaje-inject-generator</artifactId>
    <version>${avaje.inject.version}</version>
    <scope>provided</scope>
</dependency>
```

**Comment by soenkekrusche** [comment]
oh wow, I have not thought about that. First time I encounter an issue like that!
Do you think this is something to be documented somewhere?

**Comment by SentryMan** [comment]
I'll add something to the docs
