### ISSUE TITLE
Support Lazy initialization

### ISSUE THREAD

**Issue by DaiYuANg** [avaje/avaje-inject#516]
How to make Bean is lazy, Maybe we can be using Supplier and at runtime Supplier.get() to inject instance

**Comment by SentryMan** [comment]
Inject is already pretty fast for wiring compared to other DI frameworks, for what purpose do you need lazy beans?

**Comment by SentryMan** [comment]
Rob [also answered this in another issue](https://github.com/avaje/avaje-inject/issues/165#issuecomment-981214024)

**Comment by SentryMan** [comment]
Tried using the [Provider Interface](https://avaje.io/inject/#provider)?

you can wire a bean provider for cases where you don't want to immediately instantiate.

**Comment by DaiYuANg** [comment]
Yeah, I had tried, I think this will make a lot of template code in my application cause there are many UI component need as a bean, if the DI framework support lazy initialization option that will be great.
If there is no way to implement lazy initialization, I only have provider interface

**Comment by SentryMan** [comment]
you could make a utility method to convert a supplier to a cached value. (btw you can also use `Supplier` if you like instead of `Provider`)

```java

  public static <T> Supplier<T> memoize(Supplier<T> original) {
    return new Supplier<T>() {
      Supplier<T> delegate = this::firstTime;
      boolean initialized;

      public T get() {
        return delegate.get();
      }

      private synchronized T firstTime() {
        if (!initialized) {
          T value = original.get();
          delegate = () -> value;
          initialized = true;
        }
        return delegate.get();
      }
    };
  }
```
Then you can do:

```java
@Singleton
class MyFXService {
  Supplier<MyObject> supplier;

  MyFXService(Supplier<MyObject> supplier) {
    this.supplier = memoize(supplier);
  }

  void someMethod() {
    var value = supplier.get();
    // idk do something
  }
}

**Comment by rob-bygrave** [comment]
> click a button and popup a dialog and the dialog is a bean.

@DaiYuANg can you show us what your code looks like?  I don't know much about JavaFX (nor swing) these days. So the idea of using DI to inject a dialog is something I can't easily visualise in terms of what that code actually looks like.  

To be clear I believe we are talking about "Lazy Singleton" (only 1 instance initialised lazily on demand - so a Provider<T> method with memoize to ensure the single instance).

Now currently we treat a `@Factory` `@Bean` `@Secondary` method as a `Provider<T>` ... and this is around only using secondary dependencies if another dependency doesn't exist.

So as a following thought, is that maybe we could have a `@Factory` `@Bean` `@Lazy` method is similarly registered as a Provider<T> (but this provider includes the memoize type logic to ensure only 1 instance). So, if we had that and that method was used to create the Dialog then the remaining question is how is that Provider<Dialog> actually used / wired ... what does the onButtonPress code look like / how does it use the Provider<Dialog> ?

**Comment by DaiYuANg** [comment]
> you could make a utility method to convert a supplier to a cached value. (btw you can also use `Supplier` if you like instead of `Provider`)
> 
> ```java
>   public static <T> Supplier<T> memoize(Supplier<T> original) {
>     return new Supplier<T>() {
>       Supplier<T> delegate = this::firstTime;
>       boolean initialized;
> 
>       public T get() {
>         return delegate.get();
>       }
> 
>       private synchronized T firstTime() {
>         if (!initialized) {
>           T value = original.get();
>           delegate = () -> value;
>           initialized = true;
>         }
>         return delegate.get();
>       }
>     };
>   }
> ```
> 
> Then you can do:
> 
> ```java
> @Singleton
> class MyFXService {
>   Supplier<MyObject> supplier;
> 
>   MyFXService(Supplier<MyObject> supplier) {
>     this.supplier = memoize(supplier);
>   }
> 
>   void someMethod() {
>     var value = supplier.get();
>     // idk do something
>   }
> }
> ```

Yeah, I tried the Supplier way `I think this will make a lot of template code` with the same reason, I had to xxx.get() many times

**Comment by SentryMan** [comment]
> Of course, for example:

try adding `@Secondary` to your factory beans. If I'm reading this right it should lazy load.

**Comment by rbygrave** [comment]
Yes, `@Secondary` should get the lazy initialisation for now, and yes I think we will be able to support this properly by adding a `@Lazy` to be used like:

```java
@Lazy @Bean
PreferencesFx preferencesFx() { 
 ...
```

Given this is used via `val preferencesFx = DIContext.get(PreferencesFx.class);` ... then yes that will use beanScope to obtain the instance - this part will work unchanged, all good here. Just to say, I think the alternative to the programmatic access would be to inject a `Provider<PreferencesFx>`.

So yes, I think we can add some proper support for this.

**Comment by SentryMan** [comment]
@DaiYuANg  just saying, 9.12-RC1 is in maven central so you can give this a try

**Comment by DaiYuANg** [comment]
> @DaiYuANg just saying, 9.12-RC1 is in maven central so you can give this a try

Hey, thanks so much 😸
