### ISSUE TITLE
Add @Bean(defaultCandidate=false) to match Spring v6.2.0-M1

### ISSUE THREAD

**Issue by rob-bygrave** [avaje/avaje-inject#543]
Refer: https://github.com/spring-projects/spring-framework/commit/a8fb16b47cc64d77ffdd83275aa7038a92cef767

```java

	/**
	 * Is this bean a candidate for getting autowired into some other bean based on
	 * the plain type, without any further indications such as a qualifier match?
	 * <p>Default is {@code true}; set this to {@code false} for restricted delegates
	 * that are supposed to be injectable in certain areas but are not meant to get
	 * in the way of beans of the same type in other places.
	 * <p>This is a variation of {@link #autowireCandidate()} which does not disable
	 * injection in general, just enforces an additional indication such as a qualifier.
	 * @since 6.2
	 * @see #autowireCandidate()
	 */
	boolean defaultCandidate() default true;

```

Also refer to comment from reddit:

> This will finally allow library dependencies to keep Beans they use internally private, so they can't get injected in other code just because the type happens to match.

**Comment by rbygrave** [comment]
avaje-inject is different in that we already have wiring ordering and this means we can look at a potential better solution to this issue in that, at the time a bean is registered we know the source module and at the time a bean is requested for a wiring point we know the current module being wired.

In this sense, it should be possible for avaje-inject to prioritise the wiring of a "bean local to the module" and use that as a tie breaker. In this sense we could have the good situation where developer A working on module A doesn't actually have to care or know about developer B working on module B ... for that case where they both use the same unqualified type (e.g. ObjectMapper).

That is, with avaje-inject we can use the module being wired as a tie-breaker for multiple unqualified wiring candidates.

**Comment by rbygrave** [comment]
Resolved via https://github.com/avaje/avaje-inject/pull/557 ... where avaje-inject will prefer to wire a bean that is local to the module.

This approach is available to avaje-inject due to the way it wires in an ordered way and knows the module being wired (the module that supplies a bean and the current module that is requesting a bean).
