### ISSUE TITLE
Named Map beans not working for versions > 9.10

### ISSUE THREAD

**Issue by harrel56** [avaje/avaje-inject#582]
Hello there,

while bumping dependencies (from 9.10-javax to 9.12-javax) my DI setup stopped working. I reproduced the issue in a minimal example:
```java
@Factory
public class ConfigFactory {
    @Bean
    @Named("map1")
    Map<String, Long> map1() {
        return Map.of();
    }

    @Bean
    @Named("map2")
    Map<String, String> map2(Map<String, Long> map1) {
        return Map.of();
    }
}
```
Any advice?

Thanks!

PS: Actually I just realized that dependencies injected via method arguments are not matched by name but by type - is there any way to match them by name? Something like Spring's `@Qualifier`.

**Comment by SentryMan** [comment]
have you tried
```java
@Factory
public class ConfigFactory {
    @Bean
    @Named("map1")
    Map<String, Long> map1() {
        return Map.of();
    }

    @Bean
    @Named("map2")
    Map<String, String> map2(
    @Named("map1") Map<String, Long> map1) {
        return Map.of();
    }
}
```

**Comment by harrel56** [comment]
Oh yeah, `@Named` on method param is exactly what I was looking for. But the original problem is still there regardless if I use `@Named` or not
