### ISSUE TITLE
Remove generated comment blocks

### ISSUE THREAD

**Issue by re-thc** [avaje/avaje-inject#695]
Hi, thoughts on removing the generated comments in inject? Or can this be configurable?

Is there a standard within Avaje on if a generated java file should have comments? I noticed that http `$Route` and `JsonComponent` don't but `$DI` do.

The comments in DI take up 10-30% of most files (DI files are small) and it takes up processing time when there's a lot of small files, e.g. the case when you follow the pattern of `controller` -> `service` -> `repository` -> `model` / `dto mapper` and more.

Thanks!

**Comment by SentryMan** [comment]
@rbygrave what say you

**Comment by rbygrave** [comment]
Well, the method comments in the DI classes don't really add much value, so we could remove those. 

>  it takes up processing time

I'm surprised that we think this takes a material amount of time.

> Is there a standard within Avaje on if a generated java file should have comments?

Not a standard per say but the comments are there to assist people in reading the generated code and looking to gain understanding of what is going on. For example, I think the comments in the AvajeModule are good value in that regard and I'm not keen to remove any of those.

We could remove the method comments on $DI though, those comments don't add much value.
