### ISSUE TITLE
[Question] Which modules are loaded?

### ISSUE THREAD

**Issue by mintdaniel42** [avaje/avaje-inject#696]
I have a project which uses JPMS and Avaje Inject. My question is when I have a List<interface> that is being injected and in the java.ext.lib folder (where the ServiceLoader always loads external classes from) there are other jar files that implement the AvajeModule, does the default Beanscope automatically detect them? Or do I have to change something in my module-info.java file? I know this is more about JPMS than Avaje Inject itself.
Thanks in advance 😃

**Comment by SentryMan** [comment]
> java.ext.lib folder (where the ServiceLoader always loads external classes from)

Checking the ServiceLoader javadoc, I don't see any reference. But as long as the ServiceLoader can access it, it should work. 

If the required modules are not in the class/module path at compilation, an error may be thrown. so you'll need to to add `@External` annotations to signal the modules are only available at runtime.

**Comment by mintdaniel42** [comment]
> > java.ext.lib folder (where the ServiceLoader always loads external classes from)
> 
> Checking the ServiceLoader javadoc, I don't see any reference about this. But as long as the ServiceLoader can access it, it should work.

https://docs.oracle.com/javase/tutorial/ext/basics/spi.html#packaging-service-providers-in-jar-files here it mentions the capability of the serviceloader to load from jar files in a specified folder.
