### ISSUE TITLE
Upgrading to 10.x - "Could not find any avaje modules"

### ISSUE THREAD

**Issue by harrel56** [avaje/avaje-inject#700]
Hello,

I'm trying to upgrade from 9.10-javax to 10.3-javax but now context cannot be created and an exception is thrown by `BeanScope.builder().build()`:
```
Exception in thread "main" java.lang.IllegalStateException: Could not find any avaje modules. Perhaps using Gradle and IDEA but with a setup issue? Review IntelliJ Settings / Build / Build tools / Gradle - 'Build and run using' value and set that to 'Gradle'.  Refer to https://avaje.io/inject#gradle
        at io.avaje.inject.DBeanScopeBuilder.build(DBeanScopeBuilder.java:269)
        at dev.harrel.jarhell.App.start(App.java:37)
        at dev.harrel.jarhell.App.main(App.java:25)
```

Strangely enough it only occurs when I try to run it from fat jar (running it via gradle in IJ works as expected). Tried to check if 10.x had some breaking changes but couldn't find anything. Do you have any ideas what's going on? If not, I could provide broader context.

PS Is support for javax being dropped? It looks like 10.4 version doesn't have a javax variant

**Comment by SentryMan** [comment]
when you run gradle build, do you see the classes generated correctly? Try also unzipping the fat jar and checking if they are added

**Comment by SentryMan** [comment]
also can you briefly check if this happens with earlier version of 10.x?

**Comment by harrel56** [comment]
I did check that it contained generated Module classes but nothing more than that. Gonna do a full jar diff and see if something obvious is lacking

**Comment by SentryMan** [comment]
Does it contain the generated `AvajeModule` or the old interface classes?

**Comment by harrel56** [comment]
> also can you briefly check if this happens with earlier version of 10.x?

Same error for all versions from 10.x

**Comment by SentryMan** [comment]
does the uberjar contain the meta-inf services?

**Comment by harrel56** [comment]
> Does it contain the generated AvajeModule or the old Module interface classes?

Well, there are quite a lot differences between 9.10 vs 10.3 jars. I suppose you meant something like this?

![image](https://github.com/user-attachments/assets/d9a196be-7a74-43e8-a0c2-3f8449635c3c)

**Comment by harrel56** [comment]
>  does the uberjar contain the meta-inf services?

it looks different for sure :D I can upload these 2 jars (20mb) each if you think it'll be easier to investigate

![image](https://github.com/user-attachments/assets/442366c6-2ee7-40c6-b6e4-4d91df5fa344)

**Comment by SentryMan** [comment]
> PS Is support for javax being dropped? It looks like 10.4 version doesn't have a javax variant

@rbygrave can you deploy?
