### ISSUE TITLE
Add @Sorted Annotation

### ISSUE THREAD

**Issue by mintdaniel42** [avaje/avaje-inject#723]
It would be cool if we'd have a @Sorted annotation which could be put anywhere where dependencies get injected. It only works for Lists and maybe Sets and tells the generator to use listByPriority (or probable upcoming listComparable) rather than list or set

**Comment by SentryMan** [comment]
Closing as it's been a month with no further detail, feel free to re-open if you/someone have any more arguments to support the feature
