### ISSUE TITLE
Runtime retention for Prototype annotation

### ISSUE THREAD

**Issue by iajn** [avaje/avaje-inject#746]
Related to https://github.com/avaje/avaje-inject/pull/631, which changed the retention to source.

I'd like to create a runtime check to make sure a class has the Prototype annotation, which is currently not possible since the annotation has source retention. So my request is to promote it back to runtime retention.

My use case is the following class (disregard the minor record misuse), which loads view controllers at runtime when required (e.g. opening about dialog -> load new about controller). Using singleton scope would always be an error, but it might not always/instantly be obvious since the view probably somewhat works (until it doesn't).

If the change is not possible (I'm not entirely sure what the original change was about), I guess I could work around this by checking for Singleton instead, but it's not as clean.

```java
@Prototype
@BeanTypes(ControllerFactory.class)
public record ControllerFactory(BeanScope beanScope) implements Callback<Class<?>, Object> {

    @Override
    public Object call(Class<?> type) {
        requirePrototype(type);
        return beanScope.get(type);
    }

    private void requirePrototype(Class<?> type) {
        // scope is always null here
        Prototype scope = type.getAnnotation(Prototype.class);
        Objects.requireNonNull(scope, "FXML controller must use prototype scope: " + type);
    }

}
```

**Comment by SentryMan** [comment]
Personally, I would do 

```java
  private void requireNonSingleton(Class<?> type) {
    if (type.getAnnotation(Singleton.class) != null) {
      throw new IllegalStateException("FXML controller must not use singleton scope: " + type);
    }
  }
  ```

But if you still want the runtime retention, feel free to make a PR. (Though it may take a bit to deploy what with the holidays)
