### ISSUE TITLE
Run Jakarta Dependency Injection TCK

### ISSUE THREAD

**Issue by Thihup** [avaje/avaje-inject#86]
Probably this library passes the TCK available here: https://jakarta.ee/specifications/dependency-injection/2.0/

If it passes, it would be nice to create a compatibility request in the https://github.com/eclipse-ee4j/injection-spec repo, like this one: https://github.com/eclipse-ee4j/injection-spec/issues/9

**Comment by rbygrave** [comment]
Do you want to do that?  I'm happy for people to do that.

**Comment by Thihup** [comment]
Sure. I'll just make sure that the TCK allows source annotation DI, not only runtime DI.

https://github.com/eclipse-ee4j/injection-spec/issues/10

**Comment by Thihup** [comment]
I give it a try and looks like it won't be able to pass the TCK as the TCK uses circular dependency with constructor injection, so even if they allow certify a source annotation DI, I guess this implementation will not be able to pass as it fails in the compilation with the following error:

```
[ERROR] Circular dependencies detected with beans [org.atinject.tck.auto.Seat]  To handle circular dependencies consider using field injection rather than constructor injection on one of the dependencies. 
[ERROR]    See https://avaje.io/inject/#circular
[ERROR] Circular dependency - org.atinject.tck.auto.Seat dependsOn org.atinject.tck.auto.accessories.Cupholder for org.atinject.tck.auto.accessories.Cupholder
```

**Comment by Thihup** [comment]
Looks like it used like this:

```java
public class Cupholder {

    public final Provider<Seat> seatProvider;

    @Inject
    public Cupholder(Provider<Seat> seatProvider) {
        this.seatProvider = seatProvider;
    }
}
```

```java
@Singleton
public class Seat {

    private final Cupholder cupholder;

    @Inject
    Seat(Cupholder cupholder) {
        this.cupholder = cupholder;
    }

    public Cupholder getCupholder() {
        return cupholder;
    }
}
```

I guess this could/should be supported as the type used is Provider<Seat> and not Seat. Maybe this is a bug or should be implemented the interface to the compilation succeed?

**Comment by rbygrave** [comment]
Nice work - It is a bug with avaje-inject.  

That is, given there is not a `Provider<Seat>` explicitly provided in application code the DI library is expected to provide it.  avaje-inject would be expected to detect this situation and supply a `Provider<Seat>` implementation. 
---
My suspicion is that `io.avaje.inject.spi.Builder` should have `T Provider<T> provider(Class<T> type)` method.

**Comment by rbygrave** [comment]
@Thihup  FYI The Provider option for circular dependency is now supported in versions 3.2/4.2 via https://github.com/avaje/avaje-inject/issues/92

**Comment by Thihup** [comment]
Hi.
I guess I've found another bug. It is generating the following code that doesn't compile:
```java
        $bean.fieldPlainSeatProvider = b.getProvider(jakarta.inject.Provider<org.atinject.tck.auto.Seat>.class);
        $bean.fieldDriversSeatProvider = b.getProvider(jakarta.inject.Provider<org.atinject.tck.auto.Seat>.class,"Drivers");
        $bean.fieldPlainTireProvider = b.getProvider(jakarta.inject.Provider<org.atinject.tck.auto.Tire>.class);
        $bean.fieldSpareTireProvider = b.getProvider(jakarta.inject.Provider<org.atinject.tck.auto.Tire>.class,"spare");
```
It would be good if you could take a look at the TCK sources. They are not very complicated, but might there an edge case that you could identify easily than I.

https://github.com/eclipse-ee4j/injection-tck/tree/master/src/main/java/org/atinject/tck

**Comment by rbygrave** [comment]
*> jakarta.inject.Provider<org.atinject.tck.auto.Seat>*

Just check that you are using version *4.2* [for jakarta package rather
than *3.2* which is for javax package] but I suspect you are and that this
is a different bug.


*> It would be good if you could take a look at the TCK sources. They are
not very complicated, but might there an edge case that you could identify
easily than I.*

Yeah, I'll try and have a look ...


Thanks, Rob.

**Comment by rbygrave** [comment]
This does just look like field injection of Provider<T> so yeah we don't
have a test for that.

**Comment by rbygrave** [comment]
> `$bean.fieldPlainSeatProvider = b.getProvider(jakarta.inject.Provider<org.atinject.tck.auto.Seat>.class);`

Yes, I've reproduced this using the tck.

Cheers, Rob.

**Comment by rbygrave** [comment]
Oh excellent, that is actually better than a separate spec doc imo.  Thanks for chasing that up!!

As I see it with the TCK tests we have 10 fails and those relate to injection of Fields and methods in superclasses.  That is, avaje-inject currently isn't looking for inherited field/method injection points.  

In the javadoc we see the below:

> Fields and methods in superclasses are injected before those in subclasses.

... so in terms of passing the tests in the TCK (excluding the private method/field injection that we can't do) we need to support inherited field/method injection points with a question about dealing with the case of inheriting on a type that is in a different package and has package private accessibility (ideally people would use protected for this case and keep it easy for us).

Some good improvements in the 4.4 release just made. I think the issue above is the only outstanding TCK issue.

Cheers, Rob.

**Comment by rbygrave** [comment]
Just a note to add.  There are some TCK tests that avaje-inject does not pass, these tests are with inheritance with field shadowing (field with same name on multiple levels of the inheritance hierarchy) and method shadowing (methods with same signature but different access modifier - public vs package protected etc).  The field shadowing tests seem very odd to me (I don't follow why the DI library is expected to set both fields with the same name but at different levels).  Anyway, I am currently comfortable that we are not passing those tests - happy to take feedback if someone digs into that and has a different view on it.
