### ISSUE TITLE
BeanContextBuilder is now abstract

### ISSUE THREAD

**Issue by yaskor** [avaje/avaje-inject#87]
BeanContextBuilder is now abstract...
What is the standard implementation to use instead?

**Comment by rbygrave** [comment]
I'm not sure I understand the question.  The default implementation is package protected.  We typically now obtain an implementation via `BeanContext.newBuilder()` - example in the javadoc.

Can you clarify the issue / confusion?
Thanks, Rob.

**Comment by yaskor** [comment]
That was exactly the answer I was looking for. Thank you
